/*
Command gendoctemplates writes per-function tfplugindocs templates whose frontmatter sets `subcategory:` based on which package's `Functions()` constructor registers the function. The package that returns a function from its `Functions()` is the function's family, the same source of truth Burnham uses for everything else. No name-prefix matching, no template-side dispatch. A function moved between packages picks up the new family the next time `go generate ./...` runs.

Output: one templates/functions/<name>.md.tmpl per function, written to the working tree but gitignored. tfplugindocs's per-function-template lookup picks them up automatically. Stale templates (for functions that no longer exist) are swept on each run so the directory stays in lockstep with `provider.Functions()`.

Wired to `//go:generate` in main.go and runs *before* tfplugindocs so the templates exist when tfplugindocs reads them.
*/

package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"runtime"

	"github.com/hashicorp/terraform-plugin-framework/function"

	"github.com/keeleysam/terraform-burnham/internal/provider/cedar"
	"github.com/keeleysam/terraform-burnham/internal/provider/cel"
	"github.com/keeleysam/terraform-burnham/internal/provider/color"
	"github.com/keeleysam/terraform-burnham/internal/provider/compression"
	"github.com/keeleysam/terraform-burnham/internal/provider/cryptography"
	"github.com/keeleysam/terraform-burnham/internal/provider/dataformat"
	"github.com/keeleysam/terraform-burnham/internal/provider/encoding"
	"github.com/keeleysam/terraform-burnham/internal/provider/geographic"
	"github.com/keeleysam/terraform-burnham/internal/provider/identifiers"
	"github.com/keeleysam/terraform-burnham/internal/provider/network"
	"github.com/keeleysam/terraform-burnham/internal/provider/numerics"
	"github.com/keeleysam/terraform-burnham/internal/provider/oel"
	"github.com/keeleysam/terraform-burnham/internal/provider/promql"
	"github.com/keeleysam/terraform-burnham/internal/provider/text"
	"github.com/keeleysam/terraform-burnham/internal/provider/transform"
)

// families pairs each of Burnham's function packages with the docs subcategory string the Terraform Registry should display for its members. To add a new family: add a row here. Several packages may share one subcategory (e.g. the expression-language packages cel and oel), which groups them under a single family in the Registry sidebar.
var families = []struct {
	subcategory string
	functions   []func() function.Function
}{
	{"Expression Languages", cel.Functions()},
	{"Expression Languages", cedar.Functions()},
	{"Expression Languages", oel.Functions()},
	{"Expression Languages", promql.Functions()},
	{"Compression", compression.Functions()},
	{"Structured Data", dataformat.Functions()},
	{"Networking", network.Functions()},
	{"Query and Patch", transform.Functions()},
	{"Numerics", numerics.Functions()},
	{"Identifiers", identifiers.Functions()},
	{"Text", text.Functions()},
	{"Cryptography", cryptography.Functions()},
	{"Geographic", geographic.Functions()},
	{"Encoding", encoding.Functions()},
	{"Color", color.Functions()},
}

// perFunctionTemplate mirrors tfplugindocs's defaultFunctionTemplate (internal to that module) with two additions: `subcategory` (%[1]q) is hard-coded per function instead of left empty, and an HTML comment (%[2]s, the pre-indented source list) points a reader at the files to edit. The comment sits after the YAML frontmatter so it never disturbs the front-matter parse, and renders invisibly on the Terraform Registry (HTML comments are not displayed) while being loud in the repo. Anything not specific to those two additions should match the upstream default exactly so we don't drift.
const perFunctionTemplate = `---
# generated by https://github.com/hashicorp/terraform-plugin-docs
# subcategory written by cmd/gendoctemplates; do not edit by hand
page_title: "{{.Name}} {{.Type}} - {{.RenderedProviderName}}"
subcategory: %[1]q
description: |-
{{ .Summary | plainmarkdown | trimspace | prefixlines "  " }}
---

<!--
  DO NOT EDIT. This page is generated by "go generate ./..." and any change here is overwritten on the next run.
  Edit the source instead:
%[2]s-->

# {{.Type}}: {{.Name}}

{{ .Description | trimspace }}

{{ if .HasExamples -}}
## Example Usage

{{- range .ExampleFiles }}

{{ tffile . }}
{{- end }}
{{- end }}

## Signature

{{ .FunctionSignatureMarkdown }}

## Arguments

{{ .FunctionArgumentsMarkdown }}
{{- if .HasVariadic }}
{{ .FunctionVariadicArgumentMarkdown }}
{{- end }}
`

func main() {
	log.SetFlags(0)
	log.SetPrefix("gendoctemplates: ")

	// The registry overview page (templates/index.md.tmpl) embeds the logo by absolute raw URL, which tfplugindocs cannot verify. Guard it here, in the same go:generate pipeline that runs just before tfplugindocs, so the docs are never generated pointing at a logo that is not in the tree.
	if logo := filepath.Join(repoRoot(), "assets", "logo.svg"); !fileExists(logo) {
		log.Fatalf("assets/logo.svg is missing (%s); templates/index.md.tmpl references it on the registry overview page", logo)
	}

	dst := outputDir()
	if err := os.MkdirAll(dst, 0755); err != nil {
		log.Fatalf("creating %s: %v", dst, err)
	}

	// Collect metadata by introspecting each package's Functions(). Using the framework's MetadataResponse path keeps us honest: we read whatever name the function publishes, not whatever we guess from the type name. The package directory (from the function's concrete type) locates its description file for the doc banner.
	ctx := context.Background()
	want := map[string]funcMeta{}
	for _, fam := range families {
		for _, ctor := range fam.functions {
			f := ctor()
			var resp function.MetadataResponse
			f.Metadata(ctx, function.MetadataRequest{}, &resp)
			if existing, dup := want[resp.Name]; dup {
				log.Fatalf("function %q registered in two families (%q and %q); one of them is wrong",
					resp.Name, existing.subcategory, fam.subcategory)
			}
			want[resp.Name] = funcMeta{subcategory: fam.subcategory, pkg: packageDir(f)}
		}
	}

	// Sweep stale files: any *.md.tmpl in dst that isn't for a currently-registered function gets deleted. Keeps the directory in lockstep with what `provider.Functions()` actually returns. Not strictly needed (the directory is gitignored, so stale files don't pollute commits) but it keeps `ls templates/functions/` honest while debugging.
	entries, err := os.ReadDir(dst)
	if err != nil {
		log.Fatalf("reading %s: %v", dst, err)
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		const suffix = ".md.tmpl"
		if len(name) <= len(suffix) || name[len(name)-len(suffix):] != suffix {
			continue
		}
		fnName := name[:len(name)-len(suffix)]
		if _, ok := want[fnName]; !ok {
			path := filepath.Join(dst, name)
			if err := os.Remove(path); err != nil {
				log.Fatalf("removing stale %s: %v", path, err)
			}
			log.Printf("removed stale template %s", path)
		}
	}

	root := repoRoot()
	for name, meta := range want {
		body := fmt.Sprintf(perFunctionTemplate, meta.subcategory, sourceList(root, name, meta.pkg))
		path := filepath.Join(dst, name+".md.tmpl")
		if err := os.WriteFile(path, []byte(body), 0644); err != nil {
			log.Fatalf("writing %s: %v", path, err)
		}
	}
	log.Printf("wrote %d per-function templates to %s (gitignored)", len(want), dst)
}

// funcMeta is what gendoctemplates needs to know about a registered function: the docs subcategory (family) and the package directory its Go source (and description file) live in.
type funcMeta struct {
	subcategory string
	pkg         string
}

// packageDir returns the directory name of the package that defines f (e.g. "cryptography"), taken from the concrete type's import path. That is where the function's description file lives, so the doc banner can point at it.
func packageDir(f function.Function) string {
	t := reflect.TypeOf(f)
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	return filepath.Base(t.PkgPath())
}

// sourceList builds the indented, repo-relative list of files the generated doc is assembled from, for the DO-NOT-EDIT banner. The description file must exist (it is the function's MarkdownDescription, so a missing one is a real error, guarded like the logo); the example is optional since a function need not ship one.
func sourceList(root, name, pkg string) string {
	descRel := filepath.ToSlash(filepath.Join("internal", "provider", pkg, "descriptions", name+".md"))
	if !fileExists(filepath.Join(root, descRel)) {
		log.Fatalf("description file %s for function %q is missing; the doc banner would point at a nonexistent file", descRel, name)
	}
	out := fmt.Sprintf("    prose (MarkdownDescription): %s\n", descRel)

	exampleRel := filepath.ToSlash(filepath.Join("examples", "functions", name, "function.tf"))
	if fileExists(filepath.Join(root, exampleRel)) {
		out += fmt.Sprintf("    example (Example Usage):     %s\n", exampleRel)
	}
	return out
}

// repoRoot returns the absolute path to the repository root, anchored to this main.go's source location. Same trick cmd/genpi uses, for the same reason: works under `go generate ./...` and `go run ./cmd/gendoctemplates` from any cwd.
func repoRoot() string {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		log.Fatal("runtime.Caller(0) failed; cannot locate source file")
	}
	// thisFile = .../cmd/gendoctemplates/main.go
	return filepath.Join(filepath.Dir(thisFile), "..", "..")
}

// outputDir returns the absolute path to templates/functions/.
func outputDir() string {
	return filepath.Join(repoRoot(), "templates", "functions")
}

// fileExists reports whether p exists and is a regular file.
func fileExists(p string) bool {
	info, err := os.Stat(p)
	return err == nil && !info.IsDir()
}
