/*
Command gendoctemplates writes per-function tfplugindocs templates whose frontmatter sets `subcategory:` to match the function's family.

Family membership is determined by which package's `Functions()` constructor registers the function — same source of truth Burnham uses everywhere else. This avoids the maintenance hazard of pattern-matching on function name prefixes inside a shared template.

Output layout: `templates/functions/<name>.md.tmpl` per function, plus deletion of any stale `.md.tmpl` files for functions that no longer exist.

Wired to `//go:generate` in main.go and runs *before* tfplugindocs so the templates exist when tfplugindocs reads them.
*/

package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"

	"github.com/hashicorp/terraform-plugin-framework/function"

	"github.com/keeleysam/terraform-burnham/internal/provider/dataformat"
	"github.com/keeleysam/terraform-burnham/internal/provider/network"
	"github.com/keeleysam/terraform-burnham/internal/provider/numerics"
	"github.com/keeleysam/terraform-burnham/internal/provider/transform"
)

// families pairs each of Burnham's function packages with the docs subcategory string that the Terraform Registry should display for its members. To add a new family: add a row here.
var families = []struct {
	subcategory string
	functions   []func() function.Function
}{
	{"Structured Data", dataformat.Functions()},
	{"Networking", network.Functions()},
	{"Query and Patch", transform.Functions()},
	{"Numerics", numerics.Functions()},
}

// perFunctionTemplate mirrors tfplugindocs's defaultFunctionTemplate (internal to that module) with one substitution: `subcategory` is hard-coded per function instead of left empty. The %s is replaced with the family-specific value at generation time. Anything not specific to subcategory should match the upstream default exactly so we don't drift.
const perFunctionTemplate = `---
# generated by https://github.com/hashicorp/terraform-plugin-docs
# subcategory written by cmd/gendoctemplates; do not edit by hand
page_title: "{{.Name}} {{.Type}} - {{.RenderedProviderName}}"
subcategory: %q
description: |-
{{ .Summary | plainmarkdown | trimspace | prefixlines "  " }}
---

# {{.Type}}: {{.Name}}

{{ .Description | trimspace }}

{{ if .HasExamples -}}
## Example Usage

{{- range .ExampleFiles }}

{{ tffile . }}
{{- end }}
{{- end }}

## Signature

{{ .FunctionSignatureMarkdown }}

## Arguments

{{ .FunctionArgumentsMarkdown }}
{{- if .HasVariadic }}
{{ .FunctionVariadicArgumentMarkdown }}
{{- end }}
`

func main() {
	log.SetFlags(0)
	log.SetPrefix("gendoctemplates: ")

	dst := outputDir()
	if err := os.MkdirAll(dst, 0755); err != nil {
		log.Fatalf("creating %s: %v", dst, err)
	}

	// Collect (name, subcategory) pairs by introspecting each package's Functions(). Using the framework's MetadataResponse path keeps us honest — we read whatever name the function publishes, not whatever we guess from the type name.
	ctx := context.Background()
	want := map[string]string{} // name -> subcategory
	for _, fam := range families {
		for _, ctor := range fam.functions {
			f := ctor()
			var resp function.MetadataResponse
			f.Metadata(ctx, function.MetadataRequest{}, &resp)
			if existing, dup := want[resp.Name]; dup {
				log.Fatalf("function %q registered in two families (%q and %q); one of them is wrong",
					resp.Name, existing, fam.subcategory)
			}
			want[resp.Name] = fam.subcategory
		}
	}

	// Sweep stale files: any *.md.tmpl in dst that isn't for a currently-registered function gets deleted. Keeps the directory in lockstep with what `provider.Functions()` actually returns.
	entries, err := os.ReadDir(dst)
	if err != nil {
		log.Fatalf("reading %s: %v", dst, err)
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		const suffix = ".md.tmpl"
		if len(name) <= len(suffix) || name[len(name)-len(suffix):] != suffix {
			continue
		}
		fnName := name[:len(name)-len(suffix)]
		if _, ok := want[fnName]; !ok {
			path := filepath.Join(dst, name)
			if err := os.Remove(path); err != nil {
				log.Fatalf("removing stale %s: %v", path, err)
			}
			log.Printf("removed stale template %s", path)
		}
	}

	// Write fresh templates. Sorted iteration so output ordering is deterministic if anyone needs to debug a partial run.
	for name, sub := range want {
		body := fmt.Sprintf(perFunctionTemplate, sub)
		path := filepath.Join(dst, name+".md.tmpl")
		if err := os.WriteFile(path, []byte(body), 0644); err != nil {
			log.Fatalf("writing %s: %v", path, err)
		}
	}
	log.Printf("wrote %d per-function templates under %s", len(want), dst)
}

// outputDir returns the absolute path to templates/functions/, anchored to this main.go's source location. Same trick cmd/genpi uses, for the same reason: works under `go generate ./...` and `go run ./cmd/gendoctemplates` from any cwd.
func outputDir() string {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		log.Fatal("runtime.Caller(0) failed; cannot locate source file")
	}
	// thisFile = .../cmd/gendoctemplates/main.go
	// target  = .../templates/functions
	return filepath.Join(filepath.Dir(thisFile), "..", "..", "templates", "functions")
}
