/*
Embedded packed digits of π and the runtime accessors.

pi_packed.bin holds the first 3,141,592 digits of π *following* the
decimal point, encoded as IEEE 754-2008 Densely Packed Decimal (DPD):
3 decimal digits per 10 bits, written MSB-first big-endian. 1,308,998
bytes total. The digit count is ⌊π × 10⁶⌋ — a self-referential pun
fitting RFC 3091's April-Fools spirit. The implied leading 3 of
π = 3.1415… is *not* included, per RFC 3091's "Note" section
("There MUST be an implied decimal value of 3 (three) preceding the
values provided by the service").

The file is regenerated by `go generate ./...` via cmd/genpi (which uses
the Chudnovsky binary-splitting algorithm against math/big, then
DPD-packs the result via internal/dpd). Production builds do not include
the Chudnovsky code — chudnovsky lives in a sibling subpackage that the
runtime never imports. The DPD codec is shared by genpi and runtime.
*/

//go:generate go run ./cmd/genpi

package numerics

import (
	_ "embed"

	"github.com/keeleysam/terraform-burnham/internal/provider/numerics/internal/dpd"
)

//go:embed pi_packed.bin
var piPackedBytes []byte

// piEmbeddedDigitCount is ⌊π × 10⁶⌋ — see cmd/genpi/main.go's digitCount
// for the reasoning. The two constants must stay in sync; CI verifies
// this implicitly by running `go generate ./...` and diffing pi_packed.bin.
const piEmbeddedDigitCount = 3_141_592

// readDPDTriple extracts the t-th 10-bit DPD code from the packed bytes.
// Each triple lives at bit offset t*10 (MSB-first within each byte).
//
// Because triples are 10 bits wide and we only care about t*10 bit offsets,
// `bitInByte` is always one of {0, 2, 4, 6} — never 7. So a 10-bit code
// always fits within two consecutive bytes; we never need to read a third.
// (The encoder relies on the same property to align cleanly.)
func readDPDTriple(t int64) uint16 {
	bitOffset := t * 10
	byteOffset := bitOffset >> 3
	bitInByte := uint(bitOffset & 7) // ∈ {0, 2, 4, 6}

	v := uint16(piPackedBytes[byteOffset])<<8 | uint16(piPackedBytes[byteOffset+1])
	return (v >> (16 - 10 - bitInByte)) & 0x3FF
}

// piDigitChar returns the n-th decimal digit of π *following* the decimal
// point as an ASCII byte ('0'..'9'). n is 1-indexed and must be in
// [1, piEmbeddedDigitCount]. Caller is responsible for that range check.
func piDigitChar(n int64) byte {
	idx := n - 1
	t := idx / 3
	pos := idx % 3
	d0, d1, d2 := dpd.Decode(readDPDTriple(t))
	switch pos {
	case 0:
		return '0' + d0
	case 1:
		return '0' + d1
	default:
		return '0' + d2
	}
}

// piFirstNDigits returns the first n digits of π *following* the decimal
// point as an ASCII string. n must be in [0, piEmbeddedDigitCount].
//
// Implementation: decode triples sequentially, write 3 ASCII digits per
// iteration (or fewer for the last partial triple). Single allocation.
// The final string conversion uses the same unsafe.String trick that
// strings.Builder.String() uses internally — fresh-allocated buffer never
// accessed after the conversion.
//
// Performance on Apple M4 Pro: ~14 ns for 10 digits (small n is cache-warm,
// throughput around 700 MB/s), scaling to ~9 ms for the full 3.14M digits
// at the cap. Sub-microsecond for any n ≲ 1000 — well below Terraform's
// per-function-call overhead.
func piFirstNDigits(n int64) string {
	if n <= 0 {
		return ""
	}
	out := make([]byte, n)

	fullTriples := n / 3
	for t := int64(0); t < fullTriples; t++ {
		d0, d1, d2 := dpd.Decode(readDPDTriple(t))
		out[3*t] = '0' + d0
		out[3*t+1] = '0' + d1
		out[3*t+2] = '0' + d2
	}
	// Handle the partial last triple, if any. rem ∈ {0, 1, 2}.
	switch n - fullTriples*3 {
	case 1:
		d0, _, _ := dpd.Decode(readDPDTriple(fullTriples))
		out[3*fullTriples] = '0' + d0
	case 2:
		d0, d1, _ := dpd.Decode(readDPDTriple(fullTriples))
		out[3*fullTriples] = '0' + d0
		out[3*fullTriples+1] = '0' + d1
	}

	return bytesToStringNoCopy(out)
}
