package provider

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
)

func TestAcc_MsgpackRoundtrip(t *testing.T) {
	// Encode → decode should preserve a representative value.
	runOutputTest(t,
		`output "test" {
			value = provider::burnham::msgpackdecode(
				provider::burnham::msgpackencode(
					{ name = "alice", count = 3, on = true, items = ["a", "b"] }
				)
			)
		}`,
		statecheck.ExpectKnownOutputValue("test", knownvalue.ObjectExact(map[string]knownvalue.Check{
			"name":  knownvalue.StringExact("alice"),
			"count": knownvalue.Int64Exact(3),
			"on":    knownvalue.Bool(true),
			"items": knownvalue.TupleExact([]knownvalue.Check{
				knownvalue.StringExact("a"),
				knownvalue.StringExact("b"),
			}),
		})),
	)
}

func TestAcc_MsgpackDecode_InvalidBase64(t *testing.T) {
	runErrorTest(t,
		`output "test" { value = provider::burnham::msgpackdecode("not base64!") }`,
		regexp.MustCompile(`(?i)base64|invalid`),
	)
}

func TestAcc_MsgpackDecode_BinaryFieldIsBase64String(t *testing.T) {
	// Pin the post-fix behavior: msgpack `bin` payloads come out as plain base64 strings, not plist-tagged objects. The base64 below was generated by encoding {"data": []byte{0xde, 0xad, 0xbe, 0xef}}.
	runOutputTest(t,
		`output "test" {
			value = provider::burnham::msgpackdecode("gaRkYXRhxATerb7v").data
		}`,
		statecheck.ExpectKnownOutputValue("test", knownvalue.StringExact("3q2+7w==")),
	)
}

func TestAcc_MsgpackDecode_InvalidPayload(t *testing.T) {
	// 0xc1 (base64 "wQ==") is the reserved/never-used byte in msgpack — guaranteed parse failure.
	runErrorTest(t,
		`output "test" { value = provider::burnham::msgpackdecode("wQ==") }`,
		regexp.MustCompile(`(?i)msgpack|messagepack|decode`),
	)
}
