package provider

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
)

func TestAcc_CBORRoundtrip(t *testing.T) {
	runOutputTest(t,
		`output "test" {
			value = provider::burnham::cbordecode(
				provider::burnham::cborencode(
					{ name = "alice", count = 3, on = true, items = ["a", "b"] }
				)
			)
		}`,
		statecheck.ExpectKnownOutputValue("test", knownvalue.ObjectExact(map[string]knownvalue.Check{
			"name":  knownvalue.StringExact("alice"),
			"count": knownvalue.Int64Exact(3),
			"on":    knownvalue.Bool(true),
			"items": knownvalue.TupleExact([]knownvalue.Check{
				knownvalue.StringExact("a"),
				knownvalue.StringExact("b"),
			}),
		})),
	)
}

func TestAcc_CBOREncode_DeterministicEncoding(t *testing.T) {
	// CBOR Core Deterministic Encoding sorts map keys lexicographically: { a, b } and { b, a } produce the same bytes. The base64 of a 2-element map { "a": 1, "b": 2 } in deterministic CBOR is "ompYWJqGCYY..." — assert it's stable across argument order.
	runOutputTest(t,
		`output "test" {
			value = provider::burnham::cborencode({ a = 1, b = 2 }) == provider::burnham::cborencode({ b = 2, a = 1 })
		}`,
		statecheck.ExpectKnownOutputValue("test", knownvalue.Bool(true)),
	)
}

func TestAcc_CBORDecode_ByteStringIsBase64String(t *testing.T) {
	// Pin the post-fix behavior: CBOR byte strings come out as plain base64 strings, not plist-tagged objects. The base64 below was generated by encoding {"data": []byte{0xca, 0xfe, 0xba, 0xbe}} with CoreDet.
	runOutputTest(t,
		`output "test" {
			value = provider::burnham::cbordecode("oWRkYXRhRMr+ur4=").data
		}`,
		statecheck.ExpectKnownOutputValue("test", knownvalue.StringExact("yv66vg==")),
	)
}

func TestAcc_CBORDecode_InvalidBase64(t *testing.T) {
	runErrorTest(t,
		`output "test" { value = provider::burnham::cbordecode("not base64!") }`,
		regexp.MustCompile(`(?i)base64|invalid`),
	)
}

func TestAcc_CBORDecode_NaNFloatRejected(t *testing.T) {
	// CBOR float64 NaN (major type 7, additional info 27, payload 0x7ff8000000000000) → base64 "+3/4AAAAAAAA". Regression: previously this hit `big.NewFloat(NaN)` in `goToTerraformValueImpl` which panics. Now it returns an explicit "non-finite number" error.
	runErrorTest(t,
		`output "test" { value = provider::burnham::cbordecode("+3/4AAAAAAAA") }`,
		regexp.MustCompile(`(?is)non-finite\s+number`),
	)
}

func TestAcc_CBORDecode_RejectsOversizedInput(t *testing.T) {
	// 16 MiB + 1 byte exceeds dataformatMaxInputBytes; the function rejects on length before attempting base64 decode.
	runErrorTest(t,
		`output "test" { value = provider::burnham::cbordecode(format("%-16777217s", " ")) }`,
		regexp.MustCompile(`(?is)input\s+exceeds\s+maximum\s+supported\s+length`),
	)
}
